[meta]
version = 1

[[go.apps]]
name = "go-service-api"
dir = "demo-apps/backends/go"
enabled = true

[[java.apps]]
name = "user-web"
dir = "demo-apps/backends/java"
enabled = true

[[python.apps]]
name = "python-nlp"
dir = "demo-apps/backends/python"
enabled = true

[[typescript.apps]]
name = "frontend"
dir = "demo-apps/frontends/ts"
enabled = true